name: Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add a step to create a valid tag (replace with your desired tag name)
      - name: Create a valid tag
        run: |
          git tag v1.0.${GITHUB_RUN_NUMBER}
          git push --tags

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Generate release notes
        id: release_notes
        uses: actions/github-script@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pulls } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              base: context.ref
            });

            const categorizedNotes = {
              bug: [],
              maintenance: [],
              feature: []
            };

            pulls.forEach(pull => {
              const labels = pull.labels.map(label => label.name.toLowerCase());
              const note = `- ${pull.title} (#${pull.number})`;

              if (labels.includes('bug')) {
                categorizedNotes.bug.push(note);
              } else if (labels.includes('maintenance')) {
                categorizedNotes.maintenance.push(note);
              } else if (labels.includes('feature')) {
                categorizedNotes.feature.push(note);
              }
            });

            const releaseNotes = `
              **Bugs:**
              ${categorizedNotes.bug.join('\n')}

              **Maintenance:**
              ${categorizedNotes.maintenance.join('\n')}

              **Features:**
              ${categorizedNotes.feature.join('\n')}
            `;

            return releaseNotes;

      # - name: Update Release
      #   id: update_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v1.0.${{ github.run_number }}
      #     release_name: Release v${{ github.run_number }}
      #     body: ${{ steps.release_notes.outputs.result }}
      #     draft: false
      #     prerelease: false
